Concurrency
Slavan99/scala-sbt pull request #1
Opened 2021-01-05 16:23 UTC by Slavan99

Test pull request

2021-01-05 17:11 UTC, Slavan99 commented on build.sbt
> +    ))
Some comment

2021-01-06 11:40 UTC, Slavan99 reviewed
ok

2021-01-06 11:56 UTC, Slavan99 reviewed
ок

2021-01-06 14:39 UTC, tangut requested changes

2021-01-06 22:09 UTC, Primetalk approved these changes
LGTM

2021-01-06 22:09 UTC, Primetalk commented on core/src/main/scala/concurrency/AverageWordLengthCounter.scala
> +    words.slice(startPos, endPos).map(_.length).sum
Вопрос, а не будет ли скопирован кусок массива методом slice? Как можно этого избежать?

2021-01-06 22:09 UTC, Primetalk commented on core/src/main/scala/concurrency/AverageWordLengthCounter.scala
> +    words.slice(startPos, endPos).map(_.length).sum
Полезная привычка - одно действие в строке. Гибкость Scala поощряет в одну строчку помещать слишком много...
Код пишется 1 раз, а читается 10 раз. Возможно, стоит стараться облегчить работу читателя.

2021-01-06 22:09 UTC, Primetalk commented on core/src/main/scala/concurrency/AverageWordLengthCounter.scala
> +  source.close()
В случае исключения этот код не будет вызван. 
Обычно работа с ресурсами заключается в блок try-finally, или Try{}, или cats/brackets

2021-01-06 22:09 UTC, Primetalk commented on core/src/main/scala/concurrency/AverageWordLengthCounter.scala
> +  val words: Array[String] = text.split("[\n.,\\-\";!? ]+").map(_.trim)
Можно попробовать наоборот, собрать все слова - `raw"[a-zA-Z]+".r`.
Также можно подумать, что сами слова нам не нужны, только начало-конец.
Вообще regex'ы могут быть медленными.
Можно взглянуть на fastparse - www.lihaoyi.com/fastparse/

2021-01-06 22:09 UTC, Primetalk commented on core/src/main/scala/concurrency/AverageWordLengthCounter.scala
> +  val arrayDenominator = 5
`array.sliding`?

2021-01-06 22:09 UTC, Primetalk commented on core/src/main/scala/concurrency/AverageWordLengthCounter.scala
> +  val timestamp: Long = System.currentTimeMillis / 1000
`scala.concurrent.duration`?
Возможно, лучше запомнить целиком время:
```
val startMs: Long = System.currentTimeMillis
```
а преобразования сделать в конце. Этим мы сохраним точность.

2021-01-06 22:09 UTC, Primetalk commented on core/src/main/scala/concurrency/AverageWordLengthCounter.scala
> +  val wordsLength: Int = words.length
имя немного вводит в заблуждение... `wordsCount`?

2021-01-06 22:09 UTC, Primetalk commented on core/src/main/scala/concurrency/AverageWordLengthCounter.scala
> +  // разделяем массив, каждой IO-задаче передаём подсчёт суммы слов части массива с соотв-ими индексами
два действия - (1) разделить массив и (2) посчитать. Стоит придерживаться SRP (single responsibility principle).

2021-01-06 22:09 UTC, Primetalk commented on core/src/main/scala/concurrency/AverageWordLengthCounter.scala
> +  // нашёл метод parSequence и вызвал его, чтобы запускать unsafeRunSync только один раз
:+1:

2021-01-06 22:09 UTC, Primetalk commented on core/src/main/scala/concurrency/AverageWordLengthCounter.scala
> +  private val result = ioCountersParallel.parSequence.unsafeRunSync().sum * 1.0 / wordsLength
`.unsafeRunSync()` лучше отложить до "конца мира".
Можно использовать `.map` для получения окончательного ответа прямо внутри `IO`.

2021-01-06 22:09 UTC, Primetalk commented on core/src/main/scala/concurrency/AverageWordLengthCounter.scala
> +  println("Time of multi thread calculation : " + (System.currentTimeMillis / 1000 - timestamp1) + " s")
Дважды встречается код, измеряющий время работы...
Попробуйте реализовать
```
def measure[T](io:IO[T]): IO[(T, Long)] = ???
```
- возвращает также delta ms, потребовавшиеся для вычисления `T`.

2021-01-06 22:09 UTC, Primetalk commented on core/src/main/scala/concurrency/AverageWordLengthCounter.scala
> +  executorService.shutdown()
:+1:

2021-01-19 14:29 UTC, closed without merging